name: Daily AutoText Update

on:
  schedule:
    # 15:00 UTC is 8:00 AM PST. Adjust this for your local time!
    - cron: "50 4 * * *"
  workflow_dispatch: # Allows you to click "Run workflow" manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Service Account File
        # This takes the secret you named FIREBASE_KEY and turns it back into a file
        run: echo "${{ secrets.FIREBASE_KEY }}" > serviceAccountKey.json

      - name: Run script
        run: python main.py
        env:
          # This connects your GitHub Secrets to your code
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
